### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#286]
Below are each of the modal states for Profile, Profile Delete, Sign Up, Login, Stripe, Denied Access.

- [x] Modal needs to be centered
- [x] Page needs a White Background
- [ ] Favicon and image Top Left
- [x] Modal Width 348px
- [x] Double check vertically padding between buttons and input is 20px
- [x] Default Input == #FFFFFF Fill & #232323 1PX stroke & #999999 text
- [x] Focused Input == #F7F7F7 Fill & #232323 1PX stroke & #232323 text
- [x] Hoover Input == #F7F7F7 Fill & #232323 1PX stroke & #999999 text
- [x] Error Input == #F7F7F7 Fill & #FF6565 1PX stroke & #FF6565 text
- [x] Tapping Outside (white) dismisses Modal

![EDIT PROFILE](https://user-images.githubusercontent.com/1239243/73102385-97c53b00-3ea6-11ea-98fe-74811af1f484.png)

![EDIT PROFILE – 1](https://user-images.githubusercontent.com/1239243/73102386-97c53b00-3ea6-11ea-9f1b-cd3f6c569f65.png)

![MODAL](https://user-images.githubusercontent.com/1239243/73102387-985dd180-3ea6-11ea-883d-2a0224799f0e.png)

![SIGN UP](https://user-images.githubusercontent.com/1239243/73102388-985dd180-3ea6-11ea-8ff7-f50f93fef0a7.png)

![EDIT PROFILE – 2](https://user-images.githubusercontent.com/1239243/73102391-985dd180-3ea6-11ea-861e-212c5aaadb65.png)
