### ISSUE TITLE
Epic: NPM

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#532]
- [ ] Only Capture Views.
- [ ] Organize the Projects secondary list by device rather than system type.
- [ ] Add more device sizes so we are capturing the top 10. 
- [ ] Remove HTML from being captured.
- [ ] Slim down what is being captured so that we only send 1 image to CDN for processing.
