### ISSUE TITLE
Epic: Left Nav

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#548]
**Left Nav Teams**
- [x] [Loading](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=82%3A196)

- [x] [No Team](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=82%3A1)

- [x] [One Team](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=82%3A89)

- [x] [Three Teams](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=88%3A243)

- [x] [Failed to Load](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=83%3A0)

**Left Nav Projects**

- [x] [No Project](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=82%3A89)

- [x] [Team with Project](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=88%3A280)

- [x] [Team with Project Expanded](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=88%3A302)

redo redux:
- [x] break up projects per team and store correctly
- [x] check team projects if data fetch is needed

- [x] double check parsing for unneeded data like individual accessibility
- [x] anything ‘ask page’ should be ‘team page’
- [x] anything ‘playground page’ should be ‘project page’
