### ISSUE TITLE
Epic: Magic Comment

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#549]
- [x] [No Activity Default](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=134%3A247)

- [x] [Typing Text Input Focused](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=146%3A13)

- [x] [Pasting Text Input Focused](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=146%3A125)

- [x] [Pasting Image Loading Input Focused](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=146%3A170)

- [x] [Dragging Image Loading Input Focused](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=146%3A269)

- [x] [Image Loaded Input Focused](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=146%3A457)

- [x] [Pasting URL Loading Input Focused](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=146%3A316)

- [x] [URL Image Loaded Input Focused](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=146%3A585)

- [x] [Add Code Button to Focused Input Field](https://www.figma.com/file/Q5T57DLqZJ3WtEpMwED6Wa/Web-App?node-id=196%3A273)
