### ISSUE TITLE
Epic: Adjust DB to support multiple teams

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#557]
- [x] Add `orgs` table to hold top level info
- [x] Add `orgs_teams` table to associate orgs to teams
- [x] Add `org_members` table to associate an org to member roles
- [x] Add `org_purchases` table to associate an org to a paid subscription
- [x] Add `users_purchases` table to associate an org user to a purchase
- [x] Move `type` & `domain` fields out of `teams` into `orgs` table
- [x] Add `users_teams` table for a user to have multi-team support
- [x] Add `users_builds` table for non-team users to hold their build associations

**Comment by mtholcombe** [comment]
- [ ] Add `org` table to hold top level info
- [ ] Move `type` & `domain` fields from `teams` to to `orgs` table
- [ ] Create org to team association table
- [ ] Create org to users association
