### ISSUE TITLE
Epic: Adjust APIs to support multiple teams

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#565]
## New Calls:
- [x] "ADD_TEAM"
- [x] "ADD_TEAM_MEMBER"
- [x] "ADD_ORG_TEAM"
- [x] "ADD_ORG_MEMBER"
- [x] "FETCH_ORG"
- [ ] "FETCH_ORG_TEAMS"
- [ ] "FETCH_ORG_MEMBERS"
- [ ] "FETCH_USER_TEAMS"
- [ ] "FETCH_TEAM_BUILDS"
- [ ] "FETCH_USER_BUILDS"
- [ ] "FETCH_COMPONENT_COMMENTS"
## Mod Calls:
- [ ] "REGISTER_USER"
- [ ] "FETCH_TEAM"
- [x] "FETCH_TEAM_COMMENTS"
- [x] "LOOKUP_TEAM"
- [ ] "LOOKUP_TEAM_INVITE"
- [x] "UPDATE_USER_PROFILE"
- [ ] "FETCH_BUILD_DEVICE_RENDERS"
- [ ] "FETCH_DEVICE_RENDER_TYPES"
- [ ] "FETCH_TYPE_COMPONENTS"
- [ ] "FETCH_COMPONENT"

**Comment by mtholcombe** [comment]
- [ ] Add `orgs` table to hold top level info
- [ ] Add `orgs_teams` table to associate orgs to teams
- [ ] Add `org_members` table to associate an org to member roles
- [ ] Add `org_purchases` table to associate an org to a paid subscription
- [ ] Add `users_purchases` table to associate an org user to a purchase
- [ ] Move `type` & `domain` fields out of `teams` into `orgs` table
- [ ] Add `users_teams` table for a user to have multi-team support
- [ ] Add `users_builds` table for non-team users to hold their build associations

**Comment by mtholcombe** [comment]
Content Fetching & Load Sequence:

### If user belongs to a team —
- [ ] Make call for user's teams after getting profile
- [ ] Make call for minimal build info from each users's teams to display nav plus make next calls

### If user isn't part of a team —
- [ ] Make call for minimal user's builds info to display nav plus make next build calls
- [ ] Send to user's projects summary page
- [ ] Fetch each project's minimal data to display


  ## If Ask Page —
  - [ ] Start fetching minimal data to display nav tree

    # If Ask Deeplinked:
    - [ ] Fetch active team detailed info like rules etc
    - [ ] Fetch first comment block if no comment param, otherwise start with deeplinked comment
    - [ ] Incrementally fetch rest of comment blocks

    # When Ask Navigating:
    - [ ] Start fetching details for selected team
    - [ ] Fetch first comment block, then incrementally rest of comment blocks



  ## If Project Page:
  - [ ] Start fetching minimal data to display nav tree

    # If Project Deeplinked:
    - [ ] Start fetching a build's deeplinked device render data (or default device)
    - [ ] Take active device from deeplink/parms or default and return  w/ initial grid data to display types + grid thumbs
    - [ ] Take active type / default type deeplink/parms and return base component data
    - [ ] Fetch comments & replies for the active component if w/in inner view

    # When Project Navigating
    - [ ] Start fetching device render data when switching device types from grid
    - [ ] Start fetching component data when clicking in from grid or deeplink
    - [ ] Start fetching detailed component data once inside the inner view

**Comment by mtholcombe** [comment]
# Content Fetching & Load Sequence:
## If user belongs to a team —
- [ ] Make call for user's teams after getting profile
- [ ] Make call for minimal build info from each users's teams to display nav plus make next calls

## If user isn't part of a team —
- [ ] Make call for minimal user's builds info to display nav plus make next build calls
- [ ] Send to user's projects summary page
- [ ] Fetch each project's minimal data to display


## If Ask Page —
- [ ] Start fetching minimal data to display nav tree

  ### If Ask Deeplinked:
  - [ ] Fetch active team detailed info like rules etc
  - [ ] Fetch first comment block if no comment param, otherwise start with deeplinked comment
  - [ ] Incrementally fetch rest of comment blocks

  ### When Ask Navigating:
  - [ ] Start fetching details for selected team
  - [ ] Fetch first comment block, then incrementally rest of comment blocks



## If Project Page:
- [ ] Start fetching minimal data to display nav tree

  ### If Project Deeplinked:
  - [ ] Start fetching a build's deeplinked device render data (or default device)
  - [ ] Take active device from deeplink/parms or default and return  w/ initial grid data to display types + grid thumbs
  - [ ] Take active type / default type deeplink/parms and return base component data
  - [ ] Fetch comments & replies for the active component if w/in inner view

  ### When Project Navigating
  - [ ] Start fetching device render data when switching device types from grid
  - [ ] Start fetching component data when clicking in from grid or deeplink
  - [ ] Start fetching detailed component data once inside the inner view
