### ISSUE TITLE
Stripe Epic

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#570]
- [x] We want to use Stripe's [Checkout](https://stripe.com/docs/payments/checkout) feature as Single Call To Action Button from our website to the Checkout page.
- [x] Generate stripe Keys
- [x] Stripe needs to be configured for monthly + yearly subscriptions 
- [x] Create product in stripe dashboard for monthly & yearly
- [x] Define api endpoint for generating payment session
- [x] Error handle session token generator
- [x] Make purchases table in db to hold in-progress payments
- [x] Test session generation from terminal before moving to front-end tasks
- [x] `yarn add` stripe npm
- [x] Check org domain member total & org type `free`
- [x] Call `loadStripe()` on their npm module when presenting modal
- [x] Generate session token after stripe object is created
- [x] Gut stripe modal view, pull out old form + submit process + stripe api calls
- [x] Add create session call to api handler file
- [x] We need the Pair's paywall to calculate the number of domain users and display a monthly total or discount for yearly.
- [x] When the user taps the the Checkout button it will redirect to stripe for checking out with their own payment method.
- [x] After checkout is complete it will redirect back to a Thank you page.
- [x] Update org type from `free` to `monthly` or `yearly`
- [x] Add org member role `cardholder` to user who made payment
- [x] Update team member who made payment to role `cardholder`
- [x] Handle error after submit if needed

**Required Views**
- [x] Paywall when/if domain has more than 10 people, all users see paywall until someone on the domain pays.
- [x] Thank you screen.
- [x] Email Receipt for initial and subscription payments.
