### ISSUE TITLE
Router Epic

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#573]
- [x] Ask
- [x] Project List Expanded
- [x] Project Grid
- [x] Project Details
- [x] Project Details Expanded
- [x] Modals

**Subtasks**:
- [x] Try npm `connected-react-router` for redux + routing
- [x] Breakup `rootReducer` and use `combineReducers()` instead
- [x] Use `shouldComponentUpdate()` to prevent multiple re-renders
